name: Reminder
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update_daily_schedule:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: owner/repo@ref
      - name: Fetch the data and save it
        run: |
            curl 'https://bscscan.com/token/token-analytics?m=normal&contractAddress=0x0522ecfe37ab2bdb5d60a99e08d1e8379bd35c00&a=0x0b5ebf9bab9b796e9408a8222efa4fbab625313f&lg=en%22' -o test.json
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "test.json"
            git push
