name: Update burn and mint data
on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update_daily_schedule:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch the data and save it
        run: |
            curl 'https://bscscan.com/token/token-analytics?m=normal&contractAddress=0x0522ecfe37ab2bdb5d60a99e08d1e8379bd35c00&a=0x0b5ebf9bab9b796e9408a8222efa4fbab625313f&lg=en' > BURNING_DATA.txt
            curl 'https://bscscan.com/token/token-analytics?m=normal&contractAddress=0x0522ecfe37ab2bdb5d60a99e08d1e8379bd35c00&a=0x7788d9db565828fd99cfdc32414958587d09ae15&lg=en' > MINTING_DATA.txt
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update data"
            git push
